name: Build and Deploy React App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # React app ke liye stable version

      # 3️⃣ Install dependencies
      - name: Install npm dependencies
        run: npm install

      # 4️⃣ Build React app
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unicsolution'
          slot-name: 'Production'
          package: build

      # 5️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Deploy to Azure Web App
      - name: Deploy React app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unicsolution'    # Azure Web App name
          package: build              # Sirf build folder deploy hoga
          slot-name: 'Production'

